version: 2

jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-js-amino
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - run: # run coverage report
          name: code-coverage
          command: 'npm run coverage'

  update_changelog:
        working_directory: ~/build
        docker:
          - image: circleci/openjdk:8-jdk
        steps:
          - setup_remote_docker:
              version: 17.11.0-ce
          - checkout
          - run:
              name: Update Changelog
              command: |
                cid=$(docker run -d -it ferrarimarco/github-changelog-generator:1.14.3 -u cybercongress -p js-amino --exclude-tags-regex .*[.].*[.].*[.].* --token $DOCS_GITHUB_TOKEN )
                docker attach $cid
                docker cp $cid:/usr/local/src/your-app/CHANGELOG.md ./CHANGELOG.md
                diff=$(git diff CHANGELOG.md)
                if [[  -n  "$diff" ]]; then
                  git config --global user.email "cybercongress42@gmail.com"
                  git config --global user.name "Cyber Admin"
                  git add CHANGELOG.md
                  git commit -m "Circle CI: Update Changelog"
                  git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/js-amino.git master
                fi

  update_doc:
    working_directory: ~/build
    docker:
      - image: squidfunk/mkdocs-material
    steps:
      - checkout
      - run:
          name: Update Docs
          working_directory: ~/workdir
          command: |
            git clone -q --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/library.git
      - deploy:
          name: Update docs from js-amino repo
          working_directory: ~/workdir/library
          command: |
            # We need to remove current files in folder to avoid duplicating renamed files
            rm -rf ./wiki/docs/js-amino/*
            cp -r ~/build/docs/. ./wiki/docs/js-amino/
            cp ~/build/README.md ./wiki/docs/js-amino/Overview.md
            cp ~/build/CHANGELOG.md ./wiki/docs/js-amino/Changelog.md
            cp ~/build/CONTRIBUTING.md ./wiki/docs/js-amino/Contributing.md
            cp ~/build/img/. -r ./wiki/docs/js-amino/img/
            git add -N wiki/docs/js-amino
            diff=$(git diff wiki/docs/js-amino/)
            if [[  -n  "$diff" ]]; then
              git config user.email "cybercongress42@gmail.com"
              git config user.name "Cyber Admin"
              git add wiki/docs/js-amino/
              git commit -m "Circle CI: Update Docs"
              # Push quietly to prevent showing the token in log
              git push -q https://${DOCS_GITHUB_TOKEN}@github.com/cybercongress/library.git master
            fi
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - update_changelog:
        filters:
          branches:
            only: master
        requires:
          - build
    - update_doc:
        filters:
          branches:
            only: master
        requires:
          - build
          - update_changelog
